export interface Local {
  id: string,
  title: string,
  description: string,
  price: string,
  discountPercentage: number,
  rating: number,
  stock: number,
  brand: string,
  category: string,
  thumbnail: string,
  images: string[],
  value: string,
  qtd: number,
}